### ISSUE TITLE
Support for updating winfsp in the msi installer

### ISSUE THREAD

**Issue by vxgmichel** [winfsp/winfsp#283]
## Enhancement Request

At the moment, it's not possible to directly update winfsp from a new installer. One must:
- find and uninstall the installed version of winfsp
- reboot
- install the new version of winfsp

This makes it hard to integrate winfsp in the update procedure of other products.

It would be nice to have the following behavior instead:
- the installer detects the existing installation
- the installer prompts the user for the update procedure
- the installer uninstall the existing version
- the installer install the new version
- the installer prompts the user for a reboot

Thanks!

**Comment by billziss-gh** [comment]
The biggest problem we have with this is that the FSD (File System Driver) cannot be unloaded after it has been loaded. (There are many reasons for this, but the primary ones are: 1) filter drivers tend to keep references to the FSD even without a file system present and 2) zombie files may be kept open by applications even when the containing file systems are gone.)

This means that for the old FSD to go away so that a new FSD can be installed a reboot is required.

I see 2 potential solutions to this:

1. Install the new FSD alongside the old one. For this to work WinFsp will have to start using a versioned namespace for its files, NTOS objects, etc. For example, the winfsp-x64.sys driver, may have to be installed in the `bin\VERSION\winfsp-x64.sys` directory (possibly with a symlink from `bin\winfsp-x64.sys`). As another example, the NTOS device name, `\Device\WinFsp.Disk` would become `\Device\WinFsp.Disk.VERSION`.

    Clearly this is a dangerous change. It would require a LOT of testing and would also likely require bumping the WinFsp version number to 2.0. For these reasons I am not fond of this change.

2. Modify the installer to continue the installation after a reboot. This is my preferred solution as it would not fundamentally change how WinFsp works. Unfortunately I am not enough of a Windows installer expert to have enough confidence that all cases would be handled. If a Windows installer expert wants to step in and help the process I am happy to work with them.

**Comment by tstordyallison** [comment]
My quick two cents - for me, it’s more about option 2 than actually wanting to be able run with the new version everyday.

In the environment I work in, desktop machines reboot every week. If we could rollout the update silently and have it apply post-reboot, that would be absolutely fine. Then we would rollout any changes that are dependent on the update in our user space code (which I expect is quite rare anyway).

**Comment by billziss-gh** [comment]
This functionality has been implemented and is currently in the private branch [`pvt-sxs`](https://github.com/winfsp/winfsp/tree/pvt-sxs). It will not be in the next release (`v1.12` - WinFsp 2022.2) but it will appear in the release after the next (`v2.0` - WinFsp 2023).

**Comment by vxgmichel** [comment]
> This functionality has been implemented

That's great! Is the reboot still required after the update?

**Comment by billziss-gh** [comment]
Currently, yes.

When WinFsp 2.0 arrives, no. The current plan for releasing the first beta of WinFsp 2.0 is sometime in late October - early November time frame.
