### ISSUE TITLE
Passthrough: Quickbooks QBW files won't open

### ISSUE THREAD

**Issue by earonesty** [winfsp/winfsp#325]
## Bug Report

Passthrough fs does not work with Quickbooks, even if you change the sector size to 512.

### How to Reproduce

If you download the trial version of Quickbooks here:

https://quickbooks.intuit.com/learn-support/en-us/new-subscriptions/download-a-trial-of-quickbooks-desktop/00/185974

And you build the passthrough.exe, and create the "sample qbw" file, and move it to a passtrhough fs, the file won't open.

- First, I tried changing the sector size to 512, thinking this was: https://github.com/billziss-gh/winfsp/issues/197.  Because otherwise you get FileSystemControl: 0x90390 (Function 228, Method 0)  Invalid device request.  

- Changing to 512 seems to evade that code path, but then again it does Control: 0x90390 (Device:0x9 Function:228 Method: 0) ... and, then you get an infinite loop of: FSCTL_GET_RETRIEVAL_POINTERS calls.

### Behaviors

- I would expect the FileSystemControl FSCTL_GET_RETRIEVAL_POINTERS to succeed the first time, and to return END OF FILE on the second call with the pointer advancement attempt - to better emulate NTFS behavior.   NTFS responds this way.

- Apparently AirFS works, but still has the FSCTL_GET_RETRIEVAL_POINTERS loop problem (making it very slow, but functional).

- This mean that there is a unknown discrepency between AirFS and Passthru that causes a failure, but it is very hard to diagnose with procman, because the the FSCTL_GET_RETRIEVAL_POINTERS loop issue (millions of calls to that function happen while trying to figure out how airfs differs from passthru).

### Environment

- OS version and build: 10.0.18362
- WinFsp version and build: 1.4.19049

**Comment by earonesty** [comment]
procmon logs:
- failure even with the 512 byte sector size: 
  https://pastebin.com/g2qa1PV3
- success with NTFS:
  https://pastebin.com/KCVwarx7
- success with AIRFS:
  https://pastebin.com/Usxrbnch
  (partial log, excluded the get retrieval spam, stops at that point, because i couldn't get it to log after that)

**Comment by billziss-gh** [comment]
In general I consider problems with passthrough lower priority, because passthrough is a tutorial file system. MEMFS is the reference file system for WinFsp and the one I use to reproduce and fix problems.

In this case it seems you have identified a genuine problem and described a potential solution. Thank you: it is rare to get a bug report that not only explains the problem well, but also describes a solution.

Looking at the documentation for [`FSCTL_GET_RETRIEVAL_POINTERS`](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_get_retrieval_pointers) it seems that it is used to get the locations of files for "disk" based file systems. It also has a secondary use of locating bad clusters on a disk and perhaps this is the information that Quickbooks is trying to access here.

WinFsp file systems are not true "disk" file systems and therefore it makes little sense to provide information about where the files are located on the "disk". However it does make sense to respond to queries about bad clusters (e.g. to say that we do not have any) and we should be able to implement this within the FSD.

BTW, have you tried mounting the file system as a network file system to see if this works around the Quickbook issue?

**Comment by billziss-gh** [comment]
Apparently NTFS does not return extent data for resident files (i.e. files that fit within the NTFS MFT). So perhaps we can consider all WinFsp files resident and mimic the NTFS response for such files.

**Comment by earonesty** [comment]
Yeah, that sounds like a great solution.   In the logs, I see one STATUS_SUCCESS followed by one STATUS_END_OF_FILE for the NTFS hits.   I'd bet that simply STATUS_END_OF_FILE would be enough.

**Comment by billziss-gh** [comment]
If I make a patch that implements `FSCTL_GET_RETRIEVAL_POINTERS` by returning STATUS_END_OF_FILE, would you be able to test it?

**Comment by earonesty** [comment]
Yes, I will test it.   I'm not sure I've built winfsp from scratch before,
tho.

**Comment by billziss-gh** [comment]
> Yes, I will test it.   I'm not sure I've built winfsp from scratch before,
> tho.

WinFsp build requirements are here:

https://github.com/billziss-gh/winfsp#building-and-running

I will see if I can provide a quick patch for this some time later.

**Comment by billziss-gh** [comment]
Turns out that there is already an implementation of `FSCTL_GET_RETRIEVAL_POINTERS` in WinFsp:

https://github.com/billziss-gh/winfsp/blob/v1.8B3/src/sys/fsctl.c#L599

The comments suggest that this was added to pass the Microsoft IfsTest file system test suite. So this complicates matters somewhat with respect to this problem.

**Comment by billziss-gh** [comment]
If you are able to build WinFsp a quick test would be to replace the code in `FspFsvolFileSystemControlGetRetrievalPointers` with simply:

```C
return STATUS_END_OF_FILE;
```

**Comment by colatkinson** [comment]
@earonesty and I were finally able to do some more testing here, using [v1.11RC1](https://github.com/winfsp/winfsp/releases/tag/v1.11RC1). Some findings:

1. QuickBooks is using [SAP SQL Anywhere](https://en.wikipedia.org/wiki/SQL_Anywhere) as an embedded DB/on-disk format. So any other software doing the same, if there is any, is likely to run into the same issue.
1. The patch you proposed above does indeed fix the issue with `FSCTL_GET_RETRIEVAL_POINTERS`. QuickBooks makes a single call, gets `STATUS_END_OF_FILE`, and stops there.
2. On the latest version, performance isn't actually too bad even without the `FSCTL_GET_RETRIEVAL_POINTERS` -- unless Procmon is running, in which case the system slows to a crawl. Presumably due to the overhead of recording all those ops.
3. The primary compatibility issue with the passthrough seems to be it returning `IndexNumber = 0` for all files. QB seems to have some internal mapping of index to file handle, and so ends up trying to use its main file (.qbw) as its transaction log (.qbw.TLG).
4. Since the new ntptfs does set `IndexNumber`, it does work out of the box with QuickBooks.

Not sure how actionable any of this is, but hopefully it's at least somewhat helpful.

**Comment by billziss-gh** [comment]
@colatkinson thank you for the update on this. Apologies for my late reply.

Passthough indeed does not set `IndexNumber`, which causes problem for some applications (notably Visual Studio). I have refrained to fix this problem, because I have always viewed passthrough as the "tutorial" file system, but I am realizing that quite a few people are using it for real work and should probably fix it.

**Comment by billziss-gh** [comment]
I have added commit 2c3800077f9efad42ead3c2e8aa78024f5481f8e, which fixes the `IndexNumber` in `GetFileInfoInternal`.
