### ISSUE TITLE
.NET Core version of the wrapper

### ISSUE THREAD

**Issue by mikelatcs** [winfsp/winfsp#374]
Hi @billziss-gh! One question. There is a .NET Core compatible version of the WinFSP wrapper, or it is .NET Framework only?

Thank you.

**Comment by billziss-gh** [comment]
At this time it is .NET framework only.

**Comment by smourier** [comment]
For what it's worth, I've tested to use winfsp-msil in a .NET project and it works fine.

The only trouble is around Windows-specific security classes. For example, `FileSystemRights`, `FileSecurity`, `GetAccessControl `method and some `FileStream `overloads do not exist in pure .NET 5+ because it's cross-platform. You must include the extra (Microsoft official) [System.IO.FileSystem.AccessControl](https://www.nuget.org/packages/System.IO.FileSystem.AccessControl/) nuget package and tweak the code a little bit, similar to what's shown here [Support for File Security in .NET Core](https://stackoverflow.com/a/61355179/403671)

**Comment by billziss-gh** [comment]
@smourier thank you for the pointers.

**Comment by billziss-gh** [comment]
Closing this as it has been resolved by PR #451.

There is now a nuget package at https://www.nuget.org/packages/winfsp.net. Note that it requires the latest WinFsp 2023 Beta.
