### ISSUE TITLE
Possible bug in the tutorial

### ISSUE THREAD

**Issue by netheril96** [winfsp/winfsp#415]
## Bug Report

In the [tutorial](https://winfsp.dev/doc/WinFsp-Tutorial/), the implementation of `ReadDirectory` seemingly contains a bug:

There is a line `memset(DirInfo, 0, sizeof *DirInfo);`. However, given that `FSP_FSCTL_STATIC_ASSERT(104 == sizeof(FSP_FSCTL_DIR_INFO),
    "sizeof(FSP_FSCTL_DIR_INFO) must be exactly 104.");`, this DOES NOT zero initialize the filename buffer. In the following copy, `memcpy(DirInfo->FileNameBuf, FindData.cFileName, Length * sizeof(WCHAR));`, the null terminator is not copied. This means if the stack is not zeroed, the filename buffer in `DirInfo` may not be null terminated, causing buffer overflow.

**Comment by billziss-gh** [comment]
Thanks for being eagle eyed. However this code is by design.

WinFsp follows a Windows kernel convention where strings passed within kernel mode and between kernel and user mode are not null terminated. Instead the string length is determined in some other fashion: often by passing [`UNICODE_STRING`](https://docs.microsoft.com/en-us/windows/win32/api/ntdef/ns-ntdef-_unicode_string) and other times by being inferred from the total length of the `struct` that the string is embedded in.

Because the `DirInfo` `struct` is part of the protocol between kernel mode and user mode, I chose to follow this Windows convention and not null terminate strings. This is not really a problem because in the Windows kernel you almost never assume null terminated strings anyway.

Here is the FSD accessing the file name in the `DirInfo` `struct` by careful calculating the string length first:

From https://github.com/winfsp/winfsp/blob/v1.10/src/sys/dirctl.c#L189-L191:

```C
            FileName.Length =
            FileName.MaximumLength = (USHORT)(DirInfoSize - sizeof(FSP_FSCTL_DIR_INFO));
            FileName.Buffer = DirInfo->FileNameBuf;
```

**Comment by netheril96** [comment]
OK
