### ISSUE TITLE
Python errors out when calling os.path.realpath inside a winfsp-mounted mount: OSError: [WinError 1005] The volume does not contain a recognized file system.

### ISSUE THREAD

**Issue by chaimmintz** [winfsp/winfsp#427]
## Bug Report

1) Mount a winfsp mount inside a directory like c:\temp\winfspmount
2) Run: /path/to/python/python.exe -c "import os; print(os.path.realpath('c:/temp/winfspmount/foo/bar'))"

### Behaviors

This will error out with the following error:
```
Traceback (most recent call last):
  File "\path\to\python\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'c:\\temp\\winfspmount\\foo\\bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "\path\to\python\python\windows\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "\path\to\python\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'c:\\temp\\winfspmount\\foo\\bar'
```

This is unexpected and it should not error out.

Googling around it seems a few other people have had this error and https://bugs.python.org/msg406212 has some more details about it from a python perspective. Is there a possible fix for this inside winfsp?

### Environment

Windows 10 (19044.1645)
Python 3.8.13
winfsp: 1.10.22006 (via FUSE2 API)

**Comment by billziss-gh** [comment]
Thanks for the report. This is a known problem.

The problem is that the `GetFinalPathNameByHandle` API (when used with the `VOLUME_NAME_DOS` flag) does not work for file systems that are not mounted via the Mount Manager. This includes file systems that are mounted as drives via `DefineDosDeviceW` or as directories via Junctions.

The solution is to mount your file system via the Mount Manager:

- When mounting as a drive specify the drive as `\\.\X:` rather than `X:`, which will instruct WinFsp to use the Mount Manager rather than `DefineDosDeviceW` for creating the drive (requires Admin privileges).

- Unfortunately WinFsp does not currently contain a method to mount a file system as a directory using the Mount Manager.

**Comment by chaimmintz** [comment]
Thank you for the quick reply

Just so I understand, in order to mount as a drive, the users would need admin privileges on their windows machines? If so, unfortunately that would be a viable workaround for me because the users don't have Admin privileges on the windows machines.

Is there plans in the near future to have WinFsp support mounting a file system as a directory using the Mount Manager? Would that require admin privileges on the windows machines as well?

Is there any other possible workaround inside WinFsp? Is that error code returned by WinFsp somewhere, or does the call not even make it to WinFsp?

**Comment by billziss-gh** [comment]
> Just so I understand, in order to mount as a drive, the users would need admin privileges on their windows machines?

Yes.

You can mount as a drive using the `X:` syntax without being an Administrator. The reason is that it creates a drive in your local session drive namespace, which does not require Administrator privileges.

If you mount using the `\\.\X:` then WinFsp uses the Mount Manager to create a global drive (visible to all users/sessions similarly to `C:`). This requires Administrator privileges.

> Is there plans in the near future to have WinFsp support mounting a file system as a directory using the Mount Manager?

I do not have any such plans currently.

> Would that require admin privileges on the windows machines as well?

I do not know for certain, but I find it likely.

> Is there any other possible workaround inside WinFsp?

Unfortunately there is no other workaround.

> Is that error code returned by WinFsp somewhere, or does the call not even make it to WinFsp?

`GetFinalPathNameByHandle` does the following for a file handle:

- Interrogates the file system servicing the file handle. WinFsp handles this part and returns the path within the file system: `\Path\To\File`.

- Translates the "NT device name" (e.g. `\Device\Volume{GUID}`) to the "DOS device name" (e.g. `X:`) when `VOLUME_NAME_DOS` is specified. This is the part that `GetFinalPathNameByHandle` is unable to handle unless the "DOS device name" was created by the Mount Manager. (WinFsp does not get a change to influence this translation.)

Personally I consider this an issue with `GetFinalPathNameByHandle`.

**Comment by chaimmintz** [comment]
Hmm this is a big bummer. It sounds like from what you are saying that any windows user-mode filesystem library would have this same issue?

Also, AppLocker seems to encounter the same error when it tries to check executables inside the mount when we try to run it, so AppLocker seems to be blocking any .exe run from the mount.

```
PS C:\> Get-AppLockerFileInformation -path C:\temp\winfspmount\foo.exe
Get-AppLockerFileInformation : The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that
the volume is not corrupted. (Exception from HRESULT: 0x800703ED)
At line:1 char:1
+ Get-AppLockerFileInformation -path C:\temp\winfspmount\foo.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AppLockerFileInformation], FileLoadException
    + FullyQualifiedErrorId : TestAppLockerPolicyCmdlet-FailedProcessingFile,Microsoft.Security.ApplicationId.PolicyManagement.Cmdlets.GetAppLockerFileInformation
   Cmdlet
```
