### ISSUE TITLE
can not run xxx.exe which requires administrator access

### ISSUE THREAD

**Issue by xuyouqiao2005** [winfsp/winfsp#436]
if we run program(eg:xxx_install.exe) which requires administrator access,  system would show tips that you can't access X:\xxx_install.exe and the error code is 0x800704b3. 

i run memfs with cmd:
memfs -i -F NTFS -m X:

**Comment by billziss-gh** [comment]
Are you creating drive X: from a local account? Then drive X: will only be visible to that account and will not be visible to any other account or to the same account elevated as Administrator. This is by design on Windows. See comments in [`DefineDosDeviceW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-definedosdevicew).

You can create the drive from the LocalSystem account and then it will be a global drive and accessible to everyone including an account elevated as Administrator. Or you can use the syntax `\\.\X:` for the drive which will instruct WinFsp to use the Mount Manager for mounting, which will also create a global drive (using the Mount Manager requires Administrator access).

**Comment by xuyouqiao2005** [comment]
Thanks replyed So quickly.

But Unfortunately, when I started powerShell which runed elevated as Administrator,  cmd `memfs-x64 -m \\.\X:` is  partial worked:
I started `xxx_install.exe` on powerShell (also runed elevated as Administrator), it runs `success`.
but when I double click `xxx_install.exe`, it runs `fail`.

Strangely, I can run any other program in poweShell(not Administrator account) with cmd `X:\test.exe` and double click test.exe also worked.
But in poweShell(also not Administrator account) cmd `X:\xxx_install.exe` runs fail.

In addition, `xxx_install.exe` need run with Administrator access

**Comment by xuyouqiao2005** [comment]
Q: Are you creating drive X: from a local account? 
A: I create drive X: from a Administrator account. And  `xxx_install.exe` UAC  require Administrator level

**Comment by issuex** [comment]
Same problem here. In consumer windows pc, user can run program as `current-user` or administrator. and winfsp only mount in `current-user` make user cannot run `*.exe` as administrator.
To fix this problem `winfsp` should have specific argument to run winfsp as `current-user` and `administrator` at the same time.

**Comment by billziss-gh** [comment]
If you make sure to specify the `-F NTFS` flag and you mount the drive using the syntax `\\.\X:` (requires Administrator access) then it should work.

In the image below I start MEMFS with the command line `memfs-x64.exe -i -F NTFS -m \\.\X:`. I then copy Cygwin's setup program (which requires Administrator access) to the drive and run it.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/15330948/194545559-7df260ee-bcb3-45e0-bf3e-5ae0ae20d88a.png">
