### ISSUE TITLE
Where are the hashes for builds?

### ISSUE THREAD

**Issue by squirrelboot** [winfsp/winfsp#439]
## Question

Why do you not publish the build hashes for these for comparison? Also the 'virustotal scan' which is currently linked to the latest download doesn't match the downloaded copy at all. 

The link to virustotal which is posted on this [page](https://github.com/winfsp/winfsp/releases/tag/v1.11), is this:
https://www.virustotal.com/gui/url/f36615fb9149ddc65b1cc4ad6e2c3641b7b703067001a29153c617e1aa6880d9

The actual file we get from this repository, the file: **winfsp-1.11.22176.msi**, has hashes:
MD5: AF6003E6F4DB9CA71E028C8C59E061C3
SHA-1: 2A58D1A8D136D59704EA23E13C50E51B177D2D08
SHA-256: 861A81364EF835DBCCD6F6564DC7D8BB8EFC94E5759BA57BA49ED56F9F35AB46

Which correspond to this [virustotal entry](https://www.virustotal.com/gui/file/861a81364ef835dbccd6f6564dc7d8bb8efc94e5759ba57ba49ed56f9f35ab46/detection/f-861a81364ef835dbccd6f6564dc7d8bb8efc94e5759ba57ba49ed56f9f35ab46-1661889430).

I feel the practice for this needs to include the build hashes with the compiled binaries. 
As currently it's completely inaccurate, despite being signed.

**Comment by billziss-gh** [comment]
The release process for WinFsp is already quite complicated and because of the requirement to perform driver signing with Microsoft requires manual steps. Publishing hashes would only make it more complicated and increase the chances of making a mistake.

Creating a GitHub release is also a manual process, where I draft the new release, upload the binary and then publish the release. Once the release has been published I manually feed the release binary URL to virustotal and I then edit the new release to include the new URL.

Obviously there are many manual steps and many opportunities for mistake here. (Perhaps all or parts of this workflow could be automated but I have not had the time or energy to do it.) Notice how you are saying that the linked release does not match what virustotal scanned and I have no idea how this would happen or how to even check that it is the case. In any case virustotal provides a "Reanalyze URL" button at the top right of its page that allows you to rescan the binary for viruses:

<img width="106" alt="image" src="https://user-images.githubusercontent.com/15330948/188173482-41320c2a-9401-40b6-8cf5-5369051ff307.png">

Finally I also do not see the point of publishing binary hashes as the release is signed and contains binaries that are signed.

**Comment by squirrelboot** [comment]
Just wanted to thank you for this.

**Comment by billziss-gh** [comment]
[WinFsp 2023 Beta2](https://github.com/winfsp/winfsp/releases/tag/v2.0B2) now has build hashes.
