### ISSUE TITLE
FileIdInformation support (was: run as administrator failed)

### ISSUE THREAD

**Issue by diyc** [winfsp/winfsp#486]
## Bug Report

run process run as administrator failed where passthrough -m \\?\P: in virtual disk.
error code:0x800704b3

### How to Reproduce

Double click to run the administrator program or Right click the menu to select Administrator Run

### Behaviors

_Provide information on the expected and actual behaviors._

### Environment

- OS version and build: 20H2
- WinFsp version and build: 2.0.23005.0

**Comment by diyc** [comment]
![image](https://user-images.githubusercontent.com/17294171/210767310-11522c09-dea4-4419-a38c-7e4f3f65683e.png)
![image](https://user-images.githubusercontent.com/17294171/210767381-6bbccd5c-a2e0-4cda-82cc-e9121f083f97.png)

**Comment by huddhudd** [comment]
me to

**Comment by CFSworks** [comment]
I am also having this problem but took the time to debug it:

What's happening is Windows is trying to open a UAC prompt to ask the user to grant the administrator privileges. The code that pops the UAC box (`csrss.exe`) is doing a `NtQueryInformationFile(..., FileIdInformation, ...);` on the executable file. But WinFsp's `FspFsvolQueryInformation` does not implement the `FileIdInformation` information class, so it errors back with `STATUS_INVALID_PARAMETER`. `csrss.exe` interprets this as an I/O problem and kills the program.

I would love to help fix this but I don't have a driver dev environment set up. For now, as a workaround, try first starting an elevated cmd/powershell prompt and launching your executable from within that.

**Comment by billziss-gh** [comment]
@CFSworks thank you for diagnosing this problem. This is very helpful!

WinFsp does not support 128-bit file ID's, but according to this [documentation](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-file_id_information) we can still support the file ID related operations and report 0 as the file ID, which should hopefully fix the problem with `csrss.exe`.

**Comment by CFSworks** [comment]
I suppose whether or not that's the right move depends on the purpose of querying `FileIdInformation`. My unscientific guess was that it's to make sure the actual UAC prompt (`consent.exe`) was displaying information about the same file that's about to run -- so that no malware could pull a switcheroo and exploit a race condition to get administrator privileges under the guise of a Windows component or similar. But I'm not seeing any evidence to support that in my procmon traces, so ultimately I have no idea.

**Comment by billziss-gh** [comment]
A few alternatives for 128-bit file ID support:

1. Use the existing 64-bit "index numbers" (analogous to inode numbers on Unix) and zero-extend them to 128-bit.

2. Ask the file systems to supply the 128-bit file ID's. Backwards incompatible.

3. Calculate the 128-bit file ID from the file name (e.g. hash) which is unique in WinFsp file systems, because they do not support hard links. Forwards incompatible if WinFsp ever gets hard link support.

4. Return 0 (which is a legal value according to the documentation). Perharps `csrss.exe` will fall back to more widely supported "index numbers" for their checking (although one would think that they would already do that if `FileIdInformation` queries fail).

I find that option 1 may be the best after all. Thoughts?

**Comment by CFSworks** [comment]
Of those I also like option 1 the best, though I'd suggest doing the 64-to-128 extension with a magic number (like `0x57696e4673704080`, `"WinFsp" + {64, 128}`) instead of zero padding, since that both makes it clear what extended the ID and helps keep the IDs unique in case WinFsp ever gains support for 128-bit IDs in the future.

On my end, I found that the offending query, though still made by `csrss.exe`, is actually made by the `InternalSxsCreateProcess` function in `sxssrv.dll`. I now doubt that it had much to do with UAC after all, but I am thinking that the call was added to fix `CVE-2019-0735`, the writeup of which criticized `sxssrv.dll` for keying the SxS manifest cache on `(file path, write timestamp)` and allowing a sort of cache poisoning attack to give system executables a malicious SxS manifest by first launching a malicious binary with an identical path and timestamp (the writeup mentions getting the malicious binary at the same path by using impersonation and redirecting the system drive; my NT knowledge is nowhere near deep enough to know what this means). Presumably Microsoft switched to keying the cache on `(volume serial, 128-bit ID, write timestamp)` instead.

So, there are security implications to what we do here: **we need to make sure there's no way for an unprivileged attacker to use a WinFsp volume to create/write an unprivileged binary with the same serial+ID combo as a privileged binary.** (And if we aren't confident we can do that, I guess we're supposed to use an ID of 0 to disable the SxS cache? That would trade performance for security, if so.)

I suppose since nobody puts privileged system binaries in WinFsp volumes, the risk is virtually nil, unless it's somehow possible to engineer a situation where the WinFsp volume serial matches the system volume serial? But even then the "magic number" should help mitigate any vulnerabilities, so I still say option 1 is the right choice, but I'm also a bit out of my depth here so it's up to you.

**Comment by billziss-gh** [comment]
FYI, I have an initial implementation of `FileIdInformation` support which returns a non-0 file ID based on the `IndexNumber`.

However I am finding that no `FileIdInformation` queries are ever performed (i.e. no breakpoint gets hit) when attempting to launch executables that launch UAC from a WinFsp local drive mounted via the `\\.\X:` syntax (at least on Win10 1909, which I use for kernel debugging).

**Comment by billziss-gh** [comment]
I now have an implementation of `FileIdInformation` that returns non-0 file ID's based on `IndexNumber`.

The `csrss.exe` process does indeed issue a `FileIdInformation` query, but the UAC procedure still fails. I am investigating.

**Comment by billziss-gh** [comment]
Turns out that this is not related to `FileIdInformation` and that WinFsp does support elevation.

Unfortunately this requires the file system name to be "NTFS". (This seems to be hardcoded in Windows.) For example, this works:

```
memfs-x64 -i -F NTFS -m \\.\X:
```

See #355.

Regarding `FileIdInformation` support: After poking around `InternalSxsCreateProcess` I do not believe that it requires support for `FileIdInformation`, as it seems to handle gracefully an erroneous return from `NtQueryInformationFile` / `FileIdInformation`. Nevertheless it may be worthwhile to implement `FileIdInformation` sometime in the future, but we are too close to final release of WinFsp 2023 and I do not want to change any kernel code unless it fixes an actual bug.

I will open a new issue asking for `FileIdInformation` support and close this one.
