### ISSUE TITLE
The Chocolatey package shows that the package content is malicious 

### ISSUE THREAD

**Issue by tsirkin** [winfsp/winfsp#508]
## Bug Report

The Chocolatey package shows that the package content is malicious 

### How to Reproduce

See here https://community.chocolatey.org/packages/winfsp
Here is the screenshot from choco site 
![image](https://github.com/winfsp/winfsp/assets/915882/b5c677ce-56ac-43fa-a8ad-e818d16c214a)

See here for more details   
https://www.virustotal.com/gui/file/6324dc81194a6a08f97b6aeca303cf5c2325c53ede153bae9fc4378f0838c101/detection/f-6324dc81194a6a08f97b6aeca303cf5c2325c53ede153bae9fc4378f0838c101-1678967991

- WinFsp version and build: 2.0.23075

**Comment by billziss-gh** [comment]
Yes, I am aware.

I build WinFsp on a system that is protected by Windows Defender. Additionally WinFsp (latest) releases are checked [every 6 hours](https://github.com/winfsp/winfsp/actions/workflows/avm.yml) for viruses using the [avm](https://github.com/billziss-gh/avm) [workflow](https://github.com/winfsp/winfsp/blob/master/.github/workflows/avm.yml).

I used to publish VirusTotal links for WinFsp, but I no longer do so because of false positives. The problem is that VirusTotal includes too many vendors and some of them appear to apply dubious heuristics to determine if something is malware. For more information on this decision please see this [comment](https://github.com/winfsp/winfsp/issues/466#issuecomment-1413647306).
