### ISSUE TITLE
FUSE operations extra error propagation in winfsp-fuse

### ISSUE THREAD

**Issue by dmga44** [winfsp/winfsp#520]
## Enhancement request

We've been working on LizardFS Windows Client, and we would like to support as much features as possible. Our current code implements the ```fuse_operations``` structure using the FUSE3 API provided by WinFSP.

The key matter of this issue is the fact that the error codes returned by some fuse operations are not catched or handled by the latest ([2.0.23075](https://github.com/winfsp/winfsp/releases/download/v2.0/winfsp-v2.0.23075)) winfsp-fuse implementation. The actual implementation simply supposes those calls will succeed.  Some of those fuse operations and ones we are most interested in are:
- ```unlink```, you can check it [here](https://github.com/winfsp/winfsp/blob/master/src/dll/fuse/fuse_intf.c#L1343)
- ```rmdir```, you can check it [here](https://github.com/winfsp/winfsp/blob/master/src/dll/fuse/fuse_intf.c#L1338)
- ```flush```, you can check it [here](https://github.com/winfsp/winfsp/blob/master/src/dll/fuse/fuse_intf.c#L1370)

##### Motivation examples:
The next examples depicts our need for having this error propagation to the upper layers of the WinFSP architecture:
1 - Suppose you have a LizardFS read-only file system, mounted with our current client and you delete a file/folder. While watching at the logs of this test we checked that the ```unlink```/```rmdir``` operation returns an error code ( error ```-30``` translated to ```STATUS_MEDIA_WRITE_PROTECTED```) and the other fuse operations succeed, as expected, but at UI the operation succeeds and the file/folder is apparently deleted. When you refresh explorer it appears again, as the operation did not succeed for real.
2 - Suppose you have a file with replication goal ec(3,1) on a LizardFS file system mounted with our current client. It means the file uses erasure coding with 3 data parts and 1 parity part. You can read more about erasure coding [here](https://en.wikipedia.org/wiki/Erasure_code). It specially means that when you have only 2 chunkservers active, you should not be able to write to the file, and you should not be able to read from the file if non-empty. An empty file might be opened by common tools like notepad on Windows UI and when writing and trying to save its content you expect the operation to fail. In our tests, like in the previous example, it succeeds apparently. It does not save the new content of the file. In the expected sequence of calls, the ```flush``` fuse operation is the only call expected to fail with error ```-22``` translated to ```STATUS_INVALID_PARAMETER```. The ```flush``` call from this example in our implementation returns the expected error code. There is also a ```truncate``` call which is returning the same error code (probably a call to ```SetFileSize``` from the ```FSP_FILE_SYSTEM_INTERFACE``` implementation for winfsp-fuse). The bottom line is that the ```flush``` call is treated like a succeeding one, and it is not.

We would appreciate any comments on how to solve previous issues and any work done on this matter by WinFSP team.

**Comment by billziss-gh** [comment]
Apologies for my late response. I was away for a long while due to a family matter.

You are correct that the WinFsp-FUSE implementation ignores the error codes from `unlink`/`rmdir` and `flush`. The reason is that these operations are performed in WinFsp-FUSE when the `HANDLE` to the underlying file is closed and Windows does not provide a way for a file system driver to return an error code from `CloseHandle`.

## `unlink` / `rmdir`

On Windows file and directory removal (`unlink`/`rmdir`) is treated as the following sequence of operations:

- `Open`: Open the file with `DELETE` access.

-  `SetInformation / Disposition`: Set the "disposition" flag on the file. The file system checks if it can delete the file and if it can it marks the file as "delete pending". If this operation reports success, the file system has "promised" that it will delete the file in the future, but it has not yet deleted the file. In general Windows file systems use this operation to check if a directory is empty.

- `Close`: Close the file. At this point the file system actually deletes the file (this also depends on whether the file is deleted using the pre-Win10 legacy behavior or the newer Win10 posix-like behavior, but I will ignore those differences for this discussion). There is no way to report an error code from this operation.

As you can see, when the `unlink` / `rmdir` happens in the FUSE API, it is too late to report an error. For this reason, WinFsp-FUSE provides an alternative: the capability `FSP_FUSE_CAP_DELETE_ACCESS`. If this capability is specified, WinFsp-FUSE will call the `access` method with the WinFsp-specific flag `FSP_FUSE_DELETE_OK` to check whether a file or directory deletion should be allowed. Admittedly this is a workaround, but it is the best that can be done within the Windows file system model.

# `flush`

The `flush` operation happens on Linux when a file descriptor is closed; it can be used to return an error from `close`. As already mentioned the equivalent `CloseHandle` API on Windows cannot report such errors.

I personally never use `flush` on my file systems (including on Linux) as it does not work reliably with memory mapped files in this scenario:

```
fd = open(...);
p = mmap(..., fd, ...);
e = close(fd); // Linux will send flush to the file system, but it will succeed since nothing has been written
assert(0 == e);
*p = 42;
munmap(p, ...); // Linux will eventually send release to the file system, but without additional flush
```

For a discussion see: https://github.com/winfsp/winfsp/issues/365#issuecomment-843635904

**Comment by dmga44** [comment]
Thank you very much for your comments. The ideas provided seems to be very helpful.
