### ISSUE TITLE
How to load large set of files in chunks?

### ISSUE THREAD

**Issue by grbharad** [winfsp/winfsp#529]
Using winfsp, I wish to load a directory which has more than 100k files. I have winfsp set up for dotnet. 

I am currently using `ReadDirectoryEntry` in which I have implemented an API call which fetches all the records at once. This became a bottleneck and I thought of paginate the API to load the files in chunks but I am unable to find a way with `ReadDirectoryEntry` to do that.

Files do not load in the File Explorer until I `return false` from `ReadDirectoryEntry` which actually means that its a end of loop while I have more files to load. 

Is there a way to load the files in the File Explorer with current files in buffer while loading the next set of files into buffer?

**Comment by billziss-gh** [comment]
The `ReadDirectory` operation can be implemented in a number of different ways:

- The default is to use [`SeekableReadDirectory`](https://github.com/winfsp/winfsp/blob/v2.0/src/dotnet/FileSystemBase.cs#L1328), which allows you to perform pagination of a directory using the `Marker` string that is passed to [`ReadDirectoryEntry`](https://github.com/winfsp/winfsp/blob/v2.0/src/dotnet/FileSystemBase.cs#L723). That is if you receive a non-null `Marker` you must return files with names "greater than" that `Marker` in the directory order determined by the file system (the order is not important as long as it remains **consistent** across `ReadDirectory` requests).

- The option of using [`BufferedReadDirectory`](https://github.com/winfsp/winfsp/blob/v2.0/src/dotnet/FileSystemBase.cs#L1352) would not suit your case, because you want directory pagination and not to read the whole directory at once.

- A final option is to override [`ReadDirectory`](https://github.com/winfsp/winfsp/blob/v2.0/src/dotnet/FileSystemBase.cs#L723) and implement it yourself. In this case you even have the opton to impement `ReadDirectory` in an asynchronous manner: you can return `STATUS_PENDING` from `ReadDirectory`, compute your response asynchronously and send it when you are ready with [`SendReadDirectoryResponse`](https://github.com/winfsp/winfsp/blob/v2.0/src/dotnet/FileSystemHost.cs#L585`)
