### ISSUE TITLE
Return STATUS_PENDING in Create Callback.

### ISSUE THREAD

**Issue by jgh0721** [winfsp/winfsp#547]
I have a question about the STATUS_PENDING feature in WinFSP. 

I would like to authenticate the user under certain conditions when a file is created or opened (i.e. when CreateFile of Win32 API is called). Also, since authentication can take some time, I would like to return STATUS_PENDING in the Create Callback and complete the request afterwards. Is this possible? Currently, the API only mentions STATUS_PENDING for Read, Write, and ReadDirectory.

**Comment by billziss-gh** [comment]
It is not possible to return STATUS_PENDING from the Create or Open callbacks.

The original reasoning was that opening a file in Windows is a synchronous operation. For this reason this limitation was also baked in the WinFsp API.

**Comment by hach-que** [comment]
@billziss-gh I'm guessing by this you mean that the call is synchronous for client software (i.e. when software calls `CreateFile`, it will always be synchronous for user mode), not that it's synchronous inside the kernel.

In my filesystems, I do run into the issue where the number of blocked threads in user mode is a bottleneck, even though I could handle a much higher throughput if all of the WinFsp callbacks supported `STATUS_PENDING`.

I dug into the source code a bit, but I can't figure out where code disallows anything other than `Read`, `Write` or `ReadDirectory` from returning `STATUS_PENDING`. It looks like the thing that currently desires the API being synchronous is the user mode `FspFileSystemDispatcherThread`, since it runs a loop whereby the response of the previous synchronous call is passed back into `FspFsctlTransact`.

However, `FspFileSystemDispatcherThread` handles `STATUS_PENDING` in a generic way and doesn't seem like it would limit it to only those calls, so I'm not sure where the limitation is actually imposed. I feel like an application that replaced the `FspFileSystemDispatcherThread` with it's own loop could manage a pool of in-flight asynchronous requests, calling `FspFsctlTransact` with responses for any call when it has them, but I suspect I'm missing some kind of lock semantics that makes this idea not work.

On another note of interest, it looks like `FspFsctlTransact` has a `Batch` mode flag, but I can't see this used outside of test code. From the looks of things, it would allow a caller using `FspFsctlTransact` to receive multiple requests from the driver in a single context switch, which could help with throughput. It also looks like `FspFsctlTransact` already allows multiple responses to be sent to the driver in the `Response` buffer, regardless of the mode.

**Comment by hach-que** [comment]
Oh, huh. `FspFsctlTransact` is actually an exported symbol in the WinFsp DLL, so implementing an alternative to the dispatcher loop seems rather trivial. The real work then becomes re-implementing the functions inside `fsop.c` that are bound to `FileSystem->Operations`, since at the very least things like `FspFileSystemOpCreate_FileCreate` assume synchronous operation by using stack memory for the `FileInfo` buffer that `Create`/`CreateEx` is expected to write to.

**Comment by billziss-gh** [comment]
@hach-que 

> I'm guessing by this you mean that the call is synchronous for client software (i.e. when software calls CreateFile, it will always be synchronous for user mode), not that it's synchronous inside the kernel.

I/O in Windows is encapsulated in "I/O Request Packets" (IRP's). Whenever a system call or other system component needs to perform an I/O operation it creates an IRP to describe that operation. The IRP is routed via the kernel I/O Manager to the appropriate subsystem or driver that will perform the operation described by the IRP. Once the operation has been performed, the subsystem or driver "completes" the IRP to inform the rest of the system about the performed operation.

The completion code is one of the familiar `NTSTATUS` codes, usually `STATUS_SUCCESS` or an error code, but it can also be `STATUS_PENDING` which informs the system that the IRP has been accepted, but is not completed yet. This makes Windows I/O inherently asynchronous, because the completion of an IRP may be postponed with `STATUS_PENDING`. At a later time the driver or subsystem may complete the IRP with a STATUS_SUCCESS or error code.

In many cases Windows system calls expose this asynchronicity to client software. However some system calls do not. A notable such call is `NtCreateFile`. `NtCreateFile` results in the creation of an `IRP_MJ_CREATE` IRP that gets posted to the appropriate file system driver. However `NtCreateFile` can only function in synchronous mode: if the file system driver responds with `STATUS_PENDING`, `NtCreateFile` will wait until the IRP completes.

Hopefully this explains my earlier comment: "The original reasoning was that opening a file in Windows is a synchronous operation."

> The real work then becomes re-implementing the functions inside fsop.c that are bound to FileSystem->Operations, since at the very least things like FspFileSystemOpCreate_FileCreate assume synchronous operation by using stack memory for the FileInfo buffer that Create/CreateEx is expected to write to.

Your observations are correct. It is actually possible to return `STATUS_PENDING` for any file system operation. It is just that the current WinFsp API only supports it for `Read`, `Write` and `ReadDirectory` out of the box.

**Comment by billziss-gh** [comment]
I am closing this as I have no plans to change the WinFsp API to allow for `STATUS_PENDING` from `Create`/`Open`.
