### ISSUE TITLE
FileNotFound issue when using NtCreateFile for parent directory

### ISSUE THREAD

**Issue by guenhter** [winfsp/winfsp#561]
Hi,

I have an issue deleting a whole folder and its hierarchy from within my program. 
First I thought it is a problem with the standard library of my programming language Rust. After I opened an issue there (https://github.com/rust-lang/rust/issues/126576) with the help of the incredible Rust community we narrowed down the problem and the chance is high, that the issue is in this driver. 

What we narrowed down:

This is my folder hierarchy (to be deleted):

```
  foo
    bar
       some.txt
```

To delete this hierarchy, my code is doing the following high level operations (just pseudo code) with the standard functions `CreateFileW` and `NtCreateFile`:

```rust
let foo_dir = CreateFileW(...);
let bar_dir = NtCreateFile(parent=foo_dir, ...);
let some_file = NtCreateFile(parent=bar_dir, ...);  // This line returns now an error - code: 53, kind: NotFound
```

This problem happens only with this WINFSP driver for SFTP. I tried some alternatives, and there the operatoins work without a problem.

Do you have any idea why this could happen?

**Comment by billziss-gh** [comment]
@guenhter 

Using your C program I was able to confirm that this problem happens against the MEMFS file system, which is the reference file system for WinFsp. Therefore this problem is not specific to SSHFS-Win, but applies to any WinFsp file system.

The problem happens only with network file systems (i.e. file systems that use are accessible via the UNC syntax `\\Server\Share` and the MUP (Multiple UNC Provider)). It does not happen with local file systems.

The specific problem is that the MUP logic fails to consider that a relative file object may reference another relative file object. The fix is to change the `if` statement to a `while` statement at this location:

https://github.com/winfsp/winfsp/blob/v2.0/src/sys/mup.c#L253-L254

**Comment by billziss-gh** [comment]
Commit 2bf9a6c16e3bba46be6ec4ade6d7c70a262d27da (currently under automated testing) should resolve this issue.

**Comment by billziss-gh** [comment]
Sorry I am on vacation and without access to the necessary hardware key to produce a new build. This will have to wait for a few more weeks.

**Comment by billziss-gh** [comment]
I am now back from vacation. I am taking care of some other issues and will produce a new build soon.

**Comment by guenhter** [comment]
Thx. The fix works like a charm.

**Comment by billziss-gh** [comment]
@supercooltest2024 

When the kernel I/O manager services an `NtCreateFile` it creates a new `FILE_OBJECT` data structure that is going to contain the information about the newly opened file, if the open succeeds. So that first `FileObject` in the chain is a newly created object and should not be referenced by anything else.
