### ISSUE TITLE
The memfs sample program just hangs

### ISSUE THREAD

**Issue by daemonjax** [winfsp/winfsp#570]
### How to Reproduce

D:\Program Files (x86)\WinFsp\bin>memfs-x64.exe -m T:
memfs -t -1 -n 1024 -s 16777216 -m T:
The service memfs has been started.

***it just hangs here, and there is no T: drive***

### Behaviors

It just hangs.  Gotta X out of the admin command prompt window.  
The service is running.  I can stop and restart the service just fine.
Nothing in windows event logs related to this, except for logs saying it was successfully installed.

### Environment
- CPU: AMD 5700x3d
- OS version and build: Win10x64 pro, just installed it and fully updated it yesterday.
- WinFsp version and build:  Tried it with both the latest gold version and also the beta version -- they both do the same thing.

**Comment by Stardidi** [comment]
The mount point is only visible to the user that started the VFS. Are you sure that's the same user, and you don't have one running as admin?

**Comment by daemonjax** [comment]
Mmmm... You mean the service?  The Service itself is probably not running
as my login account.. The windows installer probably configures it to run
as the local service account, like most other services.  That's just how
things are done in windows.

I'd have to re-install it to check what the service runs as.

If instead you mean: is the user that you ran the memfs program the same as
the one you're trying to access the drive with... yes, of course.

**Comment by garoto** [comment]
>  I probably won't be able to use github anymore starting tomorrow due to the forced 2fa policy going into effect for me... says I have 1 day left before I lose access... I'm just not gonna do that -- too much work for a site I have no personal info on.

kthxbye

**Comment by billziss-gh** [comment]
@daemonjax

When you start MEMFS from an elevated (i.e. Administrator) command prompt the created file system is not visible to processes that are not elevated (e.g. your regular Explorer window). This is an unfortunate consequence of Windows drive design, where drives created by elevated processes are placed in a different namespace than the one that is accessible to non-elevated processes.

In order to make this work simply run MEMFS from a regular (i.e. non-Administrator) command prompt. You should now be able to access drive `T:` from your Explorer window.
